name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.x'

    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        go get github.com/sunshineplan/gohttp
        go get github.com/sunshineplan/stock
        go get golang.org/x/text/encoding/simplifiedchinese

    - name: Run Unit tests
      run: |
        go test -v -race ./...
